name: Node CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
      env:
        CI: true

  lint:
    needs: build
    steps:
      - name: lint:js
      - run: npm lint:js

      - name: lint:hbs
      - run: npm lint:hbs

  test:
    needs: [lint, build]
    steps:
      - name: test
      - run: npm test -- -r dot
